/**
 * Configure the API routes
 */

let User = require('mongoose').model('User');
let logger = global.logger;

// helper functions

function requireLogin(params) {
  const {req, res, next} = params
  if(!req.user){
    res.send({status: false, message: 'Required User Login.'})
  }else {
    return next()
  }
}


function requireRole(role, params) {
  const { req, res, next } = params;
  // if(!req.user.hasRole(role)){
  //   res.send({status: false, message: 'Required Admin role.'})
  // }else {
  //   return next()
  // }

  return next()

}

// export Yote resource API paths
let routeFilenames = [];
module.exports = function(router) {
  /**
   *
   *
   */
  routeFilenames.forEach(function(filename) {
    logger.debug("filename: " + filename);
    require('../../resources/' + filename)(router, requireLogin, requireRole);
  });
}

// New Yote resource API route names generated by the Yote CLI
routeFilenames.push('user/usersApi');
routeFilenames.push('task/tasksApi');
routeFilenames.push('flow/flowsApi');

routeFilenames.push('note/notesApi');